# Generated by Django 5.1.7 on 2025-05-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_remove_plan_description_alter_plan_max_clients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='plan',
        ),
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
