# Generated by Django 5.1.7 on 2025-05-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
