# Generated by Django 5.1.7 on 2025-06-02 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_leadchangelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeadChangeLog',
        ),
    ]
