# Generated by Django 5.1.7 on 2025-05-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_remove_lead_email_lead_budget_lead_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='propertystatus',
        ),
        migrations.AlterField(
            model_name='lead',
            name='budget',
            field=models.CharField(blank=True, choices=[('less-than-50-lakh', 'Less than 50 Lakh'), ('less-than-1-crore', 'Less than 1 Crore'), ('1-crore-to-2-crore', '1 Crore to 2 Crore'), ('2-crore-to-3-crore', '2 Crore to 3 Crore'), ('3-crore-to-4-crore', '3 Crore to 4 Crore'), ('4-crore-to-5-crore', '4 Crore to 5 Crore'), ('more-than-5-crore', 'More than 5 Crore'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(blank=True, choices=[('rupayanhousing', 'Rupayan Housing'), ('rupayancityuttara', 'Rupayan City Uttara'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='facing',
            field=models.CharField(blank=True, choices=[('east', 'East'), ('west', 'West'), ('north', 'North'), ('south', 'South'), ('north-east', 'North-East'), ('north-west', 'North-West'), ('south-east', 'South-East'), ('south-west', 'South-West'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='interestedprojectbuilding',
            field=models.CharField(blank=True, choices=[('grand-building-12', 'Grand Building 12'), ('majestic-building-5', 'Majestic Building 5'), ('skyvilla-building-3', 'Skyvilla Building 3'), ('maxus-building-8', 'Maxus Building 8'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='leadsource',
            field=models.CharField(blank=True, choices=[('sgl', 'SGL'), ('walkin', 'Walk-in'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='preference_floor',
            field=models.CharField(blank=True, choices=[('1st', '1st Floor'), ('2nd', '2nd Floor'), ('3rd', '3rd Floor'), ('4th', '4th Floor'), ('5th', '5th Floor'), ('6th', '6th Floor'), ('7th', '7th Floor'), ('8th', '8th Floor'), ('9th', '9th Floor'), ('10th', '10th Floor'), ('11th', '11th Floor'), ('12th', '12th Floor'), ('13th', '13th Floor'), ('14th', '14th Floor'), ('15th', '15th Floor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='prefferatedlocation',
            field=models.CharField(blank=True, choices=[('banani', 'Banani'), ('gulshan', 'Gulshan'), ('badda', 'Badda'), ('dhanmondi', 'Dhanmondi'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='proffession',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('engineer', 'Engineer'), ('teacher', 'Teacher'), ('student', 'Student'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='projectstatus',
            field=models.CharField(blank=True, choices=[('ready', 'Ready'), ('initial', 'Initial'), ('going', 'Going')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='projecttype',
            field=models.CharField(blank=True, choices=[('grand', 'Grand'), ('majestic', 'Majestic'), ('skyvilla', 'Skyvilla'), ('maxus', 'Maxus'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('contacted', 'Contacted'), ('won', 'Won'), ('lost', 'Lost')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='subsource',
            field=models.CharField(blank=True, choices=[('ownsource', 'Own Source'), ('referral', 'Referral'), ('doorto-door', 'Door to Door'), ('social-media', 'Social Media'), ('online-advertisement', 'Online Advertisement'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='teamleader',
            field=models.CharField(blank=True, choices=[('IKTADUL', 'Iktadul'), ('salman', 'Salman'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='unit_size',
            field=models.CharField(blank=True, choices=[('2000-2500', '2000-2500 sqft'), ('200-300', '200-300 sqft'), ('300-400', '300-400 sqft'), ('2500-3000', '2500-3000 sqft'), ('3000-3500', '3000-3500 sqft'), ('3500-4000', '3500-4000 sqft'), ('4000+', '4000+ sqft'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='view',
            field=models.CharField(blank=True, choices=[('road', 'Road'), ('park', 'Park'), ('lake', 'Lake'), ('city', 'City'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
