# Generated by Django 5.1.7 on 2025-05-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_remove_lead_interestedprojectbuilding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.AddField(
            model_name='lead',
            name='followup_by',
            field=models.CharField(blank=True, choices=[('call', 'Call'), ('email', 'Email'), ('int Meeting', 'Int Meeting'), ('Ext Meeting', 'Ext Meeting'), ('project visit', 'Project Visit'), ('sold', 'Sold'), ('onboard', 'On-board'), ('junk', 'Junk')], max_length=50, null=True, verbose_name='Follow Up By'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('lead', 'Lead'), ('prospect', 'Prospect'), ('high_prospect', 'High Prospect'), ('sold_onboard', 'Sold/On-board'), ('hold', 'Hold'), ('lost', 'Lost'), ('junk', 'Junk')], max_length=20, null=True, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_followup_by',
            field=models.CharField(blank=True, choices=[('call', 'Call'), ('email', 'Email'), ('int Meeting', 'Int Meeting'), ('Ext Meeting', 'Ext Meeting'), ('project visit', 'Project Visit'), ('sold', 'Sold'), ('onboard', 'On-board'), ('junk', 'Junk')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next Follow Up Date'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='present_address',
            field=models.CharField(blank=True, choices=[('banani', 'Banani'), ('gulshan', 'Gulshan'), ('badda', 'Badda'), ('dhanmondi', 'Dhanmondi'), ('other', 'Other')], max_length=20, null=True, verbose_name='Present Address'),
        ),
    ]
