# Generated by Django 5.1.4 on 2025-05-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_remove_lead_priority_remove_lead_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='unique_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('new', 'New'), ('lead', 'Lead'), ('prospect', 'Prospect'), ('high_prospect', 'High Prospect'), ('sold_onboard', 'Sold/On-board'), ('hold', 'Hold'), ('lost', 'Lost'), ('junk', 'Junk')], default='Lead', max_length=20, null=True, verbose_name='Lead Stage'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(default=1, max_length=11, unique=True, verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
