# Generated by Django 5.1.4 on 2025-05-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_lead_unique_id_alter_lead_lead_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='unique_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
