# Generated by Django 5.1.4 on 2025-05-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0010_alter_lead_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('new', 'New'), ('lead', 'Lead'), ('prospect', 'Prospect'), ('high_prospect', 'High Prospect'), ('sold_onboard', 'Sold/On-board'), ('hold', 'Hold'), ('lost', 'Lost'), ('junk', 'Junk')], default='lead', max_length=20, null=True, verbose_name='Lead Stage'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
