# Generated by Django 5.1.7 on 2025-05-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0012_alter_lead_phone_leadhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadhistory',
            options={},
        ),
    ]
