# Generated by Django 5.1.7 on 2025-05-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0013_alter_leadhistory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadhistory',
            name='action',
        ),
        migrations.RemoveField(
            model_name='leadhistory',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='leadhistory',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='leadhistory',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='leadhistory',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='leadhistory',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadhistory',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='leadhistory',
            name='story',
            field=models.TextField(blank=True, null=True, verbose_name='Story'),
        ),
    ]
