# Generated by Django 5.1.7 on 2025-05-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0014_remove_leadhistory_action_remove_leadhistory_lead_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeadHistory',
        ),
    ]
