# Generated by Django 5.1.7 on 2025-05-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0015_delete_leadhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(choices=[('rupayanhousing', 'Rupayan Housing'), ('rupayancityuttara', 'Rupayan City Uttara'), ('other', 'Other')], default='rupayancityuttara', max_length=20, null=True, verbose_name='Company'),
        ),
    ]
