# Generated by Django 5.1.7 on 2025-05-30 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0017_alter_lead_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('high_prospect', 'High Prospect'), ('sold_onboard', 'Sold/On-board'), ('hold', 'Hold'), ('lost', 'Lost'), ('junk', 'Junk')], default='lead', max_length=20, null=True, verbose_name='Lead Stage'),
        ),
    ]
