# Generated by Django 5.1.7 on 2025-05-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0018_alter_lead_created_by_alter_lead_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='leadsource',
            field=models.CharField(blank=True, choices=[('sgl', 'SGL'), ('walkin', 'Walk-in'), ('other', 'Other')], default='sgl', max_length=20, null=True, verbose_name='Lead Source'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='projectstatus',
            field=models.CharField(blank=True, choices=[('ready', 'Ready'), ('initial', 'Initial'), ('going', 'Going')], default='ready', max_length=20, null=True, verbose_name='Project Status'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='subsource',
            field=models.CharField(blank=True, choices=[('ownsource', 'Own Source'), ('referral', 'Referral'), ('doorto-door', 'Door to Door'), ('social-media', 'Social Media'), ('online-advertisement', 'Online Advertisement'), ('other', 'Other')], default='ownsource', max_length=20, null=True, verbose_name='Sub Source'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='teamleader',
            field=models.CharField(blank=True, choices=[('iktadul', 'Iktadul'), ('salman', 'Salman'), ('other', 'Other')], default='iktadul', max_length=20, null=True, verbose_name='Team Leader'),
        ),
    ]
