# Generated by Django 5.1.7 on 2025-05-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0020_remove_lead_updated_at_alter_lead_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified At'),
        ),
    ]
