# Generated by Django 5.1.7 on 2025-05-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0021_alter_lead_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
