# Generated by Django 5.1.4 on 2025-06-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0022_alter_lead_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='unique_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
