# Generated by Django 5.1.7 on 2025-06-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0024_leadchangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('high_prospect', 'High Prospect'), ('sold_onboard', 'Sold/On-board'), ('hold', 'Hold'), ('lost', 'Lost'), ('junk', 'Junk')], default='lead', max_length=20, null=True, verbose_name='Lead Status'),
        ),
    ]
