# Generated by Django 5.1.7 on 2025-06-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0025_alter_lead_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='profession',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('artist', 'Artist'), ('engineer', 'Engineer'), ('teacher', 'Teacher'), ('student', 'Student'), ('other', 'Other')], max_length=20, null=True, verbose_name='Profession'),
        ),
    ]
