# Generated by Django 5.1.7 on 2025-06-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0026_alter_lead_profession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={},
        ),
    ]
