# Generated by Django 5.1.7 on 2025-06-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0027_alter_lead_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
