# Generated by Django 5.1.7 on 2025-06-02 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0028_alter_lead_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must be exactly 11 digits and contain only numbers.', regex='^\\d{11}$')], verbose_name='Phone'),
        ),
    ]
